const default_commands_05 = [
  {
    name: 'Mommy',
    iconName: 'mother-nurse',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Daddy',
    iconName: '',
    iconURL:
      'https://mulberrydataset.s3.us-east-2.amazonaws.com/step_dad_parent.svg',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Hi',
    iconName: '',
    iconURL: 'https://mulberrydataset.s3.us-east-2.amazonaws.com/hello.svg',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Bye',
    iconName: 'hand-wave-outline',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Food',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Drink',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Hungry',
    iconName: '',
    iconURL: 'https://mulberrydataset.s3.us-east-2.amazonaws.com/hungry.svg',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Thirsty',
    iconName: '',
    iconURL: 'https://mulberrydataset.s3.us-east-2.amazonaws.com/thirsty.svg',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Tired',
    iconName: 'sleep',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Happy',
    iconName: '',
    iconURL: 'https://mulberrydataset.s3.us-east-2.amazonaws.com/happy_man.svg',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Sad',
    iconName: '',
    iconURL: 'https://mulberrydataset.s3.us-east-2.amazonaws.com/sad_man.svg',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Water',
    iconName: '',
    iconURL: 'https://mulberrydataset.s3.us-east-2.amazonaws.com/water.svg',
    category: '',
    timestamp: 0,
  },
  {
    name: 'No',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Yes',
    iconName: '',
    iconURL: 'https://mulberrydataset.s3.us-east-2.amazonaws.com/nod_,_to.svg',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Uh Oh',
    iconName: '',
    iconURL:
      'https://mulberrydataset.s3.us-east-2.amazonaws.com/mistake_no_wrong.svg',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Puppy',
    iconName: '',
    iconURL: 'https://mulberrydataset.s3.us-east-2.amazonaws.com/dog.svg',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Kitty',
    iconName: '',
    iconURL: 'https://mulberrydataset.s3.us-east-2.amazonaws.com/cat.svg',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Stop',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Get',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Boy',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Girl',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Play',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'You',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Me',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Good',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Thank you',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Please',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'You’re welcome',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
];

export {default_commands_05};
