const default_commands_69 = [
  {
    name: 'Hello',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Goodbye',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Stop',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Start',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Want',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Take',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Good',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Bad',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Please',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Thank you',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'You’re welcome',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Help',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Put',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Left',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Right',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Here',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Yes',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'No',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'The',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'A',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Mom',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Dad',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Brother',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
  {
    name: 'Sister',
    iconName: '',
    iconURL: '',
    category: '',
    timestamp: 0,
  },
];

export {default_commands_69};
